### ISSUE TITLE
Missing attribution?

### ISSUE THREAD

**Issue by gavanderhoorn** [IFRA-Cranfield/ros2_RobotSimulation#1]
Looking at files like [irb120_ros2_gazebo/urdf/irb120_macro.urdf.xacro](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/blob/0aa4b29a7e11d81ede661e3230e7f7defb610f15/ABBRobots/IRB120/irb120_ros2_gazebo/urdf/irb120_macro.urdf.xacro), I get the impression at least some of them came from [ros-industrial/abb_experimental](https://github.com/ros-industrial/abb_experimental).

But I can't find any mention of that repository, the original packages, nor the original authors.

I only see a large [copyright block mentioning Cranfield University](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/blob/0aa4b29a7e11d81ede661e3230e7f7defb610f15/ABBRobots/IRB120/irb120_ros2_gazebo/urdf/irb120_macro.urdf.xacro#L5-L27).

If (some of) these files did in fact originate elsewhere, please respect the license(s).

It's all liberally licensed, but there are requirements, even if you had to modify (large) parts.

If I'm mistaken, then please `/ignore`.

---

edit: there is a link to `wiki.ros.org/abb` at the bottom of the readme in the [acknowledgements](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/tree/0aa4b29a7e11d81ede661e3230e7f7defb610f15#acknowledgments) section. That's not sufficient to comply with the license though.

**Comment by MikelBueno** [comment]
Hi @gavanderhoorn, thanks for the comment. As you mention, some of the information (specifications, structure, links...) has been taken from the original .urdf files in [ros-industrial/abb_experimental](https://github.com/ros-industrial/abb_experimental) and [ros-industrial/abb](https://github.com/ros-industrial/abb), and has been adapted to ROS2.

I have updated the .urdf files of the ABB Robots in this repository -> I have added a small header on top of each .urdf file, mentioning the original COPYRIGHT owner, the authors, and where the original information comes from.

Regards,
Mikel Bueno (IFRA Group, Cranfield University)
