### ISSUE TITLE
<moveit/move_group_interface/move_group_interface_improved.h> does not exist.

### ISSUE THREAD

**Issue by ChristosPeridis** [IFRA-Cranfield/ros2_RobotSimulation#13]
Hello dear IFRA team,

I wanted to experiment with your repository for leveraging the Gazebo & moveit setup for the UR5 robot that you have available in order to use it in some Reinforcement Learning experiments. I m running Linux Ubuntu 22.04 LTS via WSL2 on Windows11 Pro. Both Windows11 Pro and Ubuntu 22.04 LTS are updated to their latest version. I have followed the instructions you have on the .readme on how to install ROS2 Humble & create my 'dev_ws'. I have clone your repository to the 'src' folder of my 'dev_ws'. However during building the workspace with your package using 'colcon build' command  I received the following error:

Finished <<< ur5_ros2_moveit2 [5.08s]
--- stderr: ros2_actions                                 
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveRP_action.cpp:44:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   44 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/moveRP_action.dir/build.make:76: CMakeFiles/moveRP_action.dir/scripts/moveRP_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:417: CMakeFiles/moveRP_action.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveG_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveYPR_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveJs_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveJ_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/moveG_action.dir/build.make:76: CMakeFiles/moveG_action.dir/scripts/moveG_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:209: CMakeFiles/moveG_action.dir/all] Error 2
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveXYZ_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/moveYPR_action.dir/build.make:76: CMakeFiles/moveYPR_action.dir/scripts/moveYPR_action.cpp.o] Error 1
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveXYZW_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[1]: *** [CMakeFiles/Makefile2:365: CMakeFiles/moveYPR_action.dir/all] Error 2
gmake[2]: *** [CMakeFiles/moveJs_action.dir/build.make:76: CMakeFiles/moveJs_action.dir/scripts/moveJs_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:183: CMakeFiles/moveJs_action.dir/all] Error 2
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveROT_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveRs_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/moveJ_action.dir/build.make:76: CMakeFiles/moveJ_action.dir/scripts/moveJ_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:157: CMakeFiles/moveJ_action.dir/all] Error 2
gmake[2]: *** [CMakeFiles/moveXYZ_action.dir/build.make:76: CMakeFiles/moveXYZ_action.dir/scripts/moveXYZ_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:339: CMakeFiles/moveXYZ_action.dir/all] Error 2
gmake[2]: *** [CMakeFiles/moveXYZW_action.dir/build.make:76: CMakeFiles/moveXYZW_action.dir/scripts/moveXYZW_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:235: CMakeFiles/moveXYZW_action.dir/all] Error 2
gmake[2]: *** [CMakeFiles/moveROT_action.dir/build.make:76: CMakeFiles/moveROT_action.dir/scripts/moveROT_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:391: CMakeFiles/moveROT_action.dir/all] Error 2
gmake[2]: *** [CMakeFiles/moveRs_action.dir/build.make:76: CMakeFiles/moveRs_action.dir/scripts/moveRs_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:313: CMakeFiles/moveRs_action.dir/all] Error 2
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveL_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/cocp5/dev_ws/src/ros2_RobotSimulation/ros2_actions/scripts/moveR_action.cpp:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/moveL_action.dir/build.make:76: CMakeFiles/moveL_action.dir/scripts/moveL_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:261: CMakeFiles/moveL_action.dir/all] Error 2
gmake[2]: *** [CMakeFiles/moveR_action.dir/build.make:76: CMakeFiles/moveR_action.dir/scripts/moveR_action.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:287: CMakeFiles/moveR_action.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< ros2_actions [16.1s, exited with code 2]

Summary: 21 packages finished [33.1s]
  1 package failed: ros2_actions
  1 package had stderr output: ros2_actions
  
  
  
  I checked the relative moveit folder in the include folder of the ROS Humble, and the only file that was existing there was the 'move_group_interface.h'.
  
How could I overcome this issue?
  
I am always at your disposal for any queries you might have regarding my set up.

Thank you very much in advance for your valuable help!

Kind regards,

Christos Peridis

**Comment by ChristosPeridis** [comment]
### _**Further Reports regarding the issue**_

In order to check if this behaviour is a result of the WSL2 setup or not I have also followed the same steps to set up the project's work space in my office's workstation computer which run Linux Ubuntu LTS nativity as its main operating system. The same issue occurred in that machine as well. Furthermore, once I receive the above mentioned error and then attempt to source the workspace I am receiving the following message:

not found: "/home/lunet/cocp5/dev_ws/install/ros2_actions/share/ros2_actions/local_setup.bash"

**Comment by MikelBueno** [comment]
Hi @ChristosPeridis, 

You are missing the step that consists of including the move_group_interface_improved.h header file into the /opt/ros/include/moveit folder in your machine. This is introduced in STEP N7 in the setup instructions and further explained here: https://github.com/IFRA-Cranfield/ros2_RobotSimulation/tree/humble/include

With regard to your last issue: 
_not found: "/home/lunet/cocp5/dev_ws/install/ros2_actions/share/ros2_actions/local_setup.bash"_

This happens when the folder is not properly sourced or built. I recommend you delete the "build", "install" and "log" folders inside your /dev_ws workspace and you **_colcon build_** everything again.

Hopefully, your issues will be fixed!

Best regards,
Mikel Bueno 
IFRA-Cranfield
