### ISSUE TITLE
Cant open UR5 in gazebo

### ISSUE THREAD

**Issue by ducbin11903** [IFRA-Cranfield/ros2_RobotSimulation#23]
i've got some problems when launch ur5 python file as below:

[INFO] [gzserver-1]: process started with pid [13068]
[INFO] [gzclient-2]: process started with pid [13070]
[INFO] [robot_state_publisher-3]: process started with pid [13072]
[INFO] [spawn_entity.py-4]: process started with pid [13074]
[robot_state_publisher-3] [INFO] [1709199250.369786213] [robot_state_publisher]: got segment base
[robot_state_publisher-3] [INFO] [1709199250.369880450] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1709199250.369894281] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-3] [INFO] [1709199250.369907135] [robot_state_publisher]: got segment flange
[robot_state_publisher-3] [INFO] [1709199250.369919011] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-3] [INFO] [1709199250.369931096] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-3] [INFO] [1709199250.369942902] [robot_state_publisher]: got segment tool0
[robot_state_publisher-3] [INFO] [1709199250.369955336] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-3] [INFO] [1709199250.369966793] [robot_state_publisher]: got segment ur_base
[robot_state_publisher-3] [INFO] [1709199250.369978669] [robot_state_publisher]: got segment world
[robot_state_publisher-3] [INFO] [1709199250.369990195] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-3] [INFO] [1709199250.370002071] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-3] [INFO] [1709199250.370014436] [robot_state_publisher]: got segment wrist_3_link
1[spawn_entity.py-4] [INFO] [1709199250.632805290] [spawn_entity]: Spawn Entity started
[spawn_entity.py-4] [INFO] [1709199250.633138578] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-4] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-4]   warnings.warn(
[spawn_entity.py-4] [INFO] [1709199250.634853568] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-4] [INFO] [1709199250.636928810] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-4] [INFO] [1709199250.637240792] [spawn_entity]: Waiting for service /spawn_entity

[spawn_entity.py-4] [INFO] [1709199251.642114909] [spawn_entity]: Calling service /spawn_entity
[gzserver-1] [WARN] [1709199251.646407211] [rcl]: Found remap rule 'model_states:=model_states'. This syntax is deprecated. Use '--ros-args --remap model_states:=model_states' instead.
[gzserver-1] [WARN] [1709199251.646559360] [rcl]: Found remap rule 'link_states:=link_states'. This syntax is deprecated. Use '--ros-args --remap link_states:=link_states' instead.
[gzserver-1] [INFO] [1709199251.650134089] [ros2_grasp.gazebo_ros_state]: Publishing states of gazebo models at [/ros2_grasp/model_states]
[gzserver-1] [INFO] [1709199251.650569159] [ros2_grasp.gazebo_ros_state]: Publishing states of gazebo links at [/ros2_grasp/link_states]
[spawn_entity.py-4] [INFO] [1709199251.942624779] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [ur5]
[gzserver-1] [INFO] [1709199251.995521717] [gazebo_ros2_control]: Loading gazebo_ros2_control plugin
[gzserver-1] [INFO] [1709199251.997664724] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in namespace: /
[gzserver-1] [INFO] [1709199251.997712227] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in ros 2 node: gazebo_ros2_control
[gzserver-1] [INFO] [1709199251.997751137] [gazebo_ros2_control]: Loading parameter files /home/ducbin/ros2_ws/install/ur5_ros2_gazebo/share/ur5_ros2_gazebo/config/ur5_controller.yaml
[gzserver-1] [INFO] [1709199251.999677587] [gazebo_ros2_control]: connected to service!! robot_state_publisher
[gzserver-1] [INFO] [1709199252.000140600] [gazebo_ros2_control]: Received urdf from param server, parsing...
[gzserver-1] gzserver: symbol lookup error: /opt/ros/humble/lib/libgazebo_ros2_control.so: undefined symbol: _ZN18hardware_interface15ResourceManager9load_urdfERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbb
[ERROR] [gzserver-1]: process has died [pid 13068, exit code 127, cmd 'gzserver /home/ducbin/ros2_ws/install/ur5_ros2_gazebo/share/ur5_ros2_gazebo/worlds/ur5.world -slibgazebo_ros_init.so -slibgazebo_ros_factory.so -slibgazebo_ros_force_system.so'].
[INFO] [spawn_entity.py-4]: process has finished cleanly [pid 13074]
[INFO] [spawner-5]: process started with pid [13201]
[spawner-5] [INFO] [1709199255.263599458] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-5] [INFO] [1709199257.277408953] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-5] [INFO] [1709199259.291682388] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-5] [INFO] [1709199261.305658608] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-5] [ERROR] [1709199263.316685762] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-5]: process has died [pid 13201, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
[INFO] [spawner-6]: process started with pid [13251]
[spawner-6] [INFO] [1709199265.844843930] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1709199267.859128377] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1709199269.874343843] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1709199271.888701095] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-6] [ERROR] [1709199273.902055980] [spawner_ur5_controller]: Controller manager not available
[ERROR] [spawner-6]: process has died [pid 13251, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner ur5_controller -c /controller_manager --ros-args'].
[ERROR] [gzclient-2]: process has died [pid 13070, exit code -11, cmd 'gzclient'].

All step before are normal. Tks for u guys help

**Comment by fjanovitz** [comment]
Please, can you share the solution you used for this problem? I'm having the same issue (and i had it before in moveit2 tutorials, but the previous solutions didn't work).
