### ISSUE TITLE
CONTROLLER MANAGER NOT AVAILABLE 

### ISSUE THREAD

**Issue by chytra3** [IFRA-Cranfield/ros2_RobotSimulation#26]
I did all the installations properly and all the controller packages are present but i am getting this error as controller manager  is not available  and also some error in  Loading parameter files panda_controller.yaml
" an error string (message, file name, or formatted message) will be truncated
[gzserver-1] [ERROR] [1712762426.399338901] [gazebo_ros2_control]: parser error Couldn't parse parameter override rule: '--param robot_description:=<?xml version="1.0" ?  "

but the same files when my friends are running in their system , there is no such error 

**The terminal log is :**

ros2 launch panda_ros2_moveit2 panda_interface.launch.py 
[INFO] [launch]: All log files can be found below /home/chytra/.ros/log/2024-04-10-20-50-15-816998-chytra-30077
[INFO] [launch]: Default logging verbosity is set to INFO

 --- Cranfield University --- 
        (c) IFRA Group        

ros2_RobotSimulation --> PANDA ROBOT
Launch file -> panda_interface.launch.py

Robot configuration:

- Cell layout:
     + Option N1: PANDA ROBOT alone.
     + Option N2: PANDA ROBOT on top of a pedestal.
  Please select: 1

- End-effector:
     + No EE variants for this robot.
[INFO] [gzserver-1]: process started with pid [30078]
[INFO] [gzclient-2]: process started with pid [30080]
[INFO] [spawn_entity.py-3]: process started with pid [30082]
[INFO] [static_transform_publisher-4]: process started with pid [30084]
[INFO] [robot_state_publisher-5]: process started with pid [30086]
[static_transform_publisher-4] [WARN] [1712762422.478853131] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-4] [INFO] [1712762422.517003713] [static_transform_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-4] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-4] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-4] from 'world' to 'base_link'
[robot_state_publisher-5] [INFO] [1712762422.559233237] [robot_state_publisher]: got segment end_effector_frame
[robot_state_publisher-5] [INFO] [1712762422.559639404] [robot_state_publisher]: got segment panda_hand
[robot_state_publisher-5] [INFO] [1712762422.559688412] [robot_state_publisher]: got segment panda_leftfinger
[robot_state_publisher-5] [INFO] [1712762422.559720011] [robot_state_publisher]: got segment panda_link0
[robot_state_publisher-5] [INFO] [1712762422.559747348] [robot_state_publisher]: got segment panda_link1
[robot_state_publisher-5] [INFO] [1712762422.559773791] [robot_state_publisher]: got segment panda_link2
[robot_state_publisher-5] [INFO] [1712762422.559800464] [robot_state_publisher]: got segment panda_link3
[robot_state_publisher-5] [INFO] [1712762422.559826760] [robot_state_publisher]: got segment panda_link4
[robot_state_publisher-5] [INFO] [1712762422.559852680] [robot_state_publisher]: got segment panda_link5
[robot_state_publisher-5] [INFO] [1712762422.559879619] [robot_state_publisher]: got segment panda_link6
[robot_state_publisher-5] [INFO] [1712762422.559905156] [robot_state_publisher]: got segment panda_link7
[robot_state_publisher-5] [INFO] [1712762422.559930500] [robot_state_publisher]: got segment panda_link8
[robot_state_publisher-5] [INFO] [1712762422.559956524] [robot_state_publisher]: got segment panda_rightfinger
[robot_state_publisher-5] [INFO] [1712762422.559983152] [robot_state_publisher]: got segment world
[spawn_entity.py-3] [INFO] [1712762423.663336869] [spawn_entity]: Spawn Entity started
[spawn_entity.py-3] [INFO] [1712762423.664368659] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-3] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-3]   warnings.warn(
[spawn_entity.py-3] [INFO] [1712762423.669789230] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-3] [INFO] [1712762423.682461718] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-3] [INFO] [1712762423.683465258] [spawn_entity]: Waiting for service /spawn_entity
[gzserver-1] [WARN] [1712762425.645150010] [rcl]: Found remap rule 'model_states:=model_states'. This syntax is deprecated. Use '--ros-args --remap model_states:=model_states' instead.
[gzserver-1] [WARN] [1712762425.645884793] [rcl]: Found remap rule 'link_states:=link_states'. This syntax is deprecated. Use '--ros-args --remap link_states:=link_states' instead.
[gzserver-1] [INFO] [1712762425.669927246] [ros2_grasp.gazebo_ros_state]: Publishing states of gazebo models at [/ros2_grasp/model_states]
[gzserver-1] [INFO] [1712762425.671777571] [ros2_grasp.gazebo_ros_state]: Publishing states of gazebo links at [/ros2_grasp/link_states]
[spawn_entity.py-3] [INFO] [1712762425.696032370] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-3] [INFO] [1712762426.265439714] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [panda]
[gzserver-1] [INFO] [1712762426.371852073] [gazebo_ros2_control]: Loading gazebo_ros2_control plugin
[gzserver-1] [INFO] [1712762426.383758528] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in namespace: /
[gzserver-1] [INFO] [1712762426.383949624] [gazebo_ros2_control]: Starting gazebo_ros2_control plugin in ros 2 node: gazebo_ros2_control
[gzserver-1] [INFO] [1712762426.394198297] [gazebo_ros2_control]: connected to service!! robot_state_publisher
[gzserver-1] [INFO] [1712762426.396132022] [gazebo_ros2_control]: Received urdf from param server, parsing...
[gzserver-1] [INFO] [1712762426.396355166] [gazebo_ros2_control]: Loading parameter files /home/chytra/dev_ws/install/panda_ros2_gazebo/share/panda_ros2_gazebo/config/panda_controller.yaml
[gzserver-1] [rcutils|error_handling.c:65] an error string (message, file name, or formatted message) will be truncated
[gzserver-1] [ERROR] [1712762426.399338901] [gazebo_ros2_control]: parser error Couldn't parse parameter override rule: '--param robot_description:=<?xml version="1.0" ?><robot name="panda"><transmission name="panda_joint1_trans"><type>transmission_interface/SimpleTransmission</type><joint name="panda_joint1"><hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface></joint><actuator name="panda_joint1_motor"><mechanicalReduction>1</mechanicalReduction></actuator></transmission><transmission name="panda_joint2_trans"><type>transmission_interface/SimpleTransmission</type><joint name="panda_joint2"><hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface></joint><actuator name="panda_joint2_motor"><mechanicalReduction>1</mechanicalReduction></actuator></transmissi, at ./src/rcl/arguments.c:343
[gzserver-1] 
[INFO] [spawn_entity.py-3]: process has finished cleanly [pid 30082]
[INFO] [spawner-6]: process started with pid [30238]
[spawner-6] [INFO] [1712762429.989689920] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1712762432.010950208] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1712762434.030649837] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1712762436.052943414] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [ERROR] [1712762438.073568862] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-6]: process has died [pid 30238, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
[INFO] [spawner-7]: process started with pid [30288]
[spawner-7] [INFO] [1712762441.936157430] [spawner_panda_arm_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1712762443.955729383] [spawner_panda_arm_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1712762445.979329911] [spawner_panda_arm_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1712762448.001306249] [spawner_panda_arm_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [ERROR] [1712762450.021742045] [spawner_panda_arm_controller]: Controller manager not available
[ERROR] [spawner-7]: process has died [pid 30288, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner panda_arm_controller -c /controller_manager --ros-args'].
[INFO] [spawner-8]: process started with pid [30329]
[spawner-8] [INFO] [1712762453.554101046] [spawner_panda_handleft_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1712762455.573604561] [spawner_panda_handleft_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1712762457.594105775] [spawner_panda_handleft_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [INFO] [1712762459.614263799] [spawner_panda_handleft_controller]: Waiting for '/controller_manager' node to exist
[spawner-8] [ERROR] [1712762461.636650464] [spawner_panda_handleft_controller]: Controller manager not available
[ERROR] [spawner-8]: process has died [pid 30329, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner panda_handleft_controller -c /controller_manager --ros-args'].
[INFO] [spawner-9]: process started with pid [30371]
[spawner-9] [INFO] [1712762465.244838456] [spawner_panda_handright_controller]: Waiting for '/controller_manager' node to exist
[spawner-9] [INFO] [1712762467.270624642] [spawner_panda_handright_controller]: Waiting for '/controller_manager' node to exist
[spawner-9] [INFO] [1712762469.293777957] [spawner_panda_handright_controller]: Waiting for '/controller_manager' node to exist
[spawner-9] [INFO] [1712762471.315332582] [spawner_panda_handright_controller]: Waiting for '/controller_manager' node to exist
[spawner-9] [ERROR] [1712762473.336833637] [spawner_panda_handright_controller]: Controller manager not available
[ERROR] [spawner-9]: process has died [pid 30371, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner panda_handright_controller -c /controller_manager --ros-args'].
[INFO] [moveJs_action-10]: process started with pid [30422]
[ERROR] [moveJs_action-10]: process has died [pid 30422, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveJs_action --ros-args -r __node:=moveJs_action --params-file /tmp/launch_params_cnzlvory --params-file /tmp/launch_params_vg7z7r5z --params-file /tmp/launch_params_injx5idf --params-file /tmp/launch_params_yfiuqqtx --params-file /tmp/launch_params_39tw1u91'].
[INFO] [moveG_action-11]: process started with pid [30424]
[ERROR] [moveG_action-11]: process has died [pid 30424, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveG_action --ros-args -r __node:=moveG_action --params-file /tmp/launch_params_98e24b_q --params-file /tmp/launch_params_zz6y2x6j --params-file /tmp/launch_params_fo721929 --params-file /tmp/launch_params_p9_0ctv7 --params-file /tmp/launch_params_99f7y28b'].
[INFO] [moveL_action-12]: process started with pid [30426]
[ERROR] [moveL_action-12]: process has died [pid 30426, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveL_action --ros-args -r __node:=moveL_action --params-file /tmp/launch_params_cf861v5u --params-file /tmp/launch_params_qhi7g7zi --params-file /tmp/launch_params_qesb5kje --params-file /tmp/launch_params_pjbeg5s7 --params-file /tmp/launch_params_dhl6t1t_'].
[INFO] [moveRs_action-13]: process started with pid [30428]
[ERROR] [moveRs_action-13]: process has died [pid 30428, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveRs_action --ros-args -r __node:=moveRs_action --params-file /tmp/launch_params_0xpmwvnn --params-file /tmp/launch_params_ycy7_o6r --params-file /tmp/launch_params_oowt1mbp --params-file /tmp/launch_params_lcphfjzj --params-file /tmp/launch_params_ukfup4dq'].
[INFO] [moveXYZ_action-14]: process started with pid [30430]
[ERROR] [moveXYZ_action-14]: process has died [pid 30430, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveXYZ_action --ros-args -r __node:=moveXYZ_action --params-file /tmp/launch_params_a48ju8p3 --params-file /tmp/launch_params_phfizuus --params-file /tmp/launch_params_4mjl30oo --params-file /tmp/launch_params_0gw7ghri --params-file /tmp/launch_params_e383iqzc'].
[INFO] [moveXYZW_action-15]: process started with pid [30432]
[ERROR] [moveXYZW_action-15]: process has died [pid 30432, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveXYZW_action --ros-args -r __node:=moveXYZW_action --params-file /tmp/launch_params_7ivyzydo --params-file /tmp/launch_params_agw5gj2t --params-file /tmp/launch_params_ob70g6yd --params-file /tmp/launch_params_5cfjjtma --params-file /tmp/launch_params_q3lr_a7o'].
[INFO] [moveYPR_action-16]: process started with pid [30434]
[ERROR] [moveYPR_action-16]: process has died [pid 30434, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveYPR_action --ros-args -r __node:=moveYPR_action --params-file /tmp/launch_params_kuxbihi6 --params-file /tmp/launch_params_8cg5yx9w --params-file /tmp/launch_params_fz8jiwt6 --params-file /tmp/launch_params_9pr9wyjz --params-file /tmp/launch_params_sc0zqcbu'].
[INFO] [moveROT_action-17]: process started with pid [30436]
[ERROR] [moveROT_action-17]: process has died [pid 30436, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveROT_action --ros-args -r __node:=moveROT_action --params-file /tmp/launch_params_h94yd1lk --params-file /tmp/launch_params_9s7h5bmi --params-file /tmp/launch_params_dyt1u58l --params-file /tmp/launch_params_b86_qbtz --params-file /tmp/launch_params_d7ocwqct'].
[INFO] [moveRP_action-18]: process started with pid [30438]
[ERROR] [moveRP_action-18]: process has died [pid 30438, exit code 127, cmd '/home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveRP_action --ros-args -r __node:=moveRP_action --params-file /tmp/launch_params_ywn58f50 --params-file /tmp/launch_params_jrxgbjr9 --params-file /tmp/launch_params_gyr0jfph --params-file /tmp/launch_params_zesxmfll --params-file /tmp/launch_params_6cks045n'].
[INFO] [attacher_action.py-19]: process started with pid [30440]
[moveJs_action-10] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveJs_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveG_action-11] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveG_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveL_action-12] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveL_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveRs_action-13] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveRs_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveXYZ_action-14] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveXYZ_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveXYZW_action-15] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveXYZW_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveYPR_action-16] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveYPR_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveROT_action-17] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveROT_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[moveRP_action-18] /home/chytra/dev_ws/install/ros2_actions/lib/ros2_actions/moveRP_action: error while loading shared libraries: libmoveit_move_group_interface.so.2.5.4: cannot open shared object file: No such file or directory
[INFO] [rviz2-20]: process started with pid [30461]
[INFO] [move_group-21]: process started with pid [30463]

![WhatsApp Image 2024-04-11 at 7 50 50 PM](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/assets/142932821/d73cf854-8b0a-468f-925c-09e48d50d582)
![WhatsApp Image 2024-04-11 at 7 50 31 PM](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/assets/142932821/3d8168cf-b685-4db7-8144-218dc20c2bdf)
****

**Comment by lxd551326** [comment]
i have some question ,did you solve it?

**Comment by lxd551326** [comment]
you can try install gazebo_humble_ros2_controler version=0.4.6,if you are using 0.4.7, i had a same question

**Comment by Rostemelov** [comment]
Were you able to solve it?

> you can try install gazebo_humble_ros2_controler version=0.4.6,if you are using 0.4.7, i had a same question

**Comment by RitishShailly** [comment]
How did you install: install gazebo_humble_ros2_controler version=0.4.6?

**Comment by RitishShailly** [comment]
> you can try install gazebo_humble_ros2_controler version=0.4.6,if you are using 0.4.7, i had a same question

How did you install gazebo_humble_ros2_controler version=0.4.6?

**Comment by cncowboy** [comment]
first uninstall 
sudo apt remove gazebo_humble_ros2_controler
then 
cd  ros2_ws/src
git clone -b 0.4.6 https://github.com/ros-controls/gazebo_ros2_control.git
cd ..
colcon build

**Comment by mm0dev** [comment]
@chytra3, **I'm encountering the same issues**. Up until a month ago, the simulation was running smoothly; however, for the past ten days, I've faced the parser error and the controller manager error.

It appears to be a recurring problem with this repository. A similar issue concerning parser problems has been documented here: https://github.com/IFRA-Cranfield/ros2_RobotSimulation/issues/27

> first uninstall sudo apt remove gazebo_humble_ros2_controler then cd ros2_ws/src git clone -b 0.4.6 https://github.com/ros-controls/gazebo_ros2_control.git cd .. colcon build

I am about to try the solution proposed by @cncowboy. _Fingers crossed_.

### Update: It works.

**Comment by HR-ES** [comment]
Try removing all of the comments in your URDF/xacro files. This is what fixed it for me.

**Comment by chytra3** [comment]
> first uninstall sudo apt remove gazebo_humble_ros2_controler then cd ros2_ws/src git clone -b 0.4.6 https://github.com/ros-controls/gazebo_ros2_control.git cd .. colcon build

thank youu 
this worked !!!
this is the only difference that i found between the working system (left one) and mine (right one )
![Screenshot from 2024-04-16 03-31-18](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/assets/142932821/7555dca3-eb8e-4932-82bc-e73ecb9b747b)
