### ISSUE TITLE
The ur5 display in gazebo will slowly fall down on its own and finally coincide with the column

### ISSUE THREAD

**Issue by Swordsoulmeye** [IFRA-Cranfield/ros2_RobotSimulation#32]
![image](https://github.com/user-attachments/assets/36050dd6-3e06-4470-b6f4-4247153526ff)
[INFO] [gzserver-1]: process started with pid [99770]
[INFO] [gzclient-2]: process started with pid [99772]
[INFO] [spawn_entity.py-3]: process started with pid [99774]
[INFO] [static_transform_publisher-4]: process started with pid [99776]
[INFO] [robot_state_publisher-5]: process started with pid [99778]
[static_transform_publisher-4] [WARN] [1726303443.165801823] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-4] [INFO] [1726303443.224480649] [static_transform_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-4] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-4] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-4] from 'world' to 'base_link'
[robot_state_publisher-5] [INFO] [1726303443.302254281] [robot_state_publisher]: got segment base
[robot_state_publisher-5] [INFO] [1726303443.302849372] [robot_state_publisher]: got segment base_link
[robot_state_publisher-5] [INFO] [1726303443.302864897] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-5] [INFO] [1726303443.302869787] [robot_state_publisher]: got segment flange
[robot_state_publisher-5] [INFO] [1726303443.302876910] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-5] [INFO] [1726303443.302881337] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-5] [INFO] [1726303443.302885203] [robot_state_publisher]: got segment tool0
[robot_state_publisher-5] [INFO] [1726303443.302888985] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-5] [INFO] [1726303443.302895019] [robot_state_publisher]: got segment ur_base
[robot_state_publisher-5] [INFO] [1726303443.302899362] [robot_state_publisher]: got segment world
[robot_state_publisher-5] [INFO] [1726303443.302903288] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-5] [INFO] [1726303443.302907055] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-5] [INFO] [1726303443.302913255] [robot_state_publisher]: got segment wrist_3_link
[spawn_entity.py-3] [INFO] [1726303444.120368768] [spawn_entity]: Spawn Entity started
[spawn_entity.py-3] [INFO] [1726303444.120695569] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-3] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-3]   warnings.warn(
[spawn_entity.py-3] [INFO] [1726303444.134620888] [spawn_entity]: Waiting for entity xml on robot_description
[gzserver-1] [WARN] [1726303444.614577101] [rcl]: Found remap rule 'model_states:=model_states'. This syntax is deprecated. Use '--ros-args --remap model_states:=model_states' instead.
[gzserver-1] [WARN] [1726303444.614766779] [rcl]: Found remap rule 'link_states:=link_states'. This syntax is deprecated. Use '--ros-args --remap link_states:=link_states' instead.
[gzserver-1] [INFO] [1726303444.625628785] [ros2_grasp.gazebo_ros_state]: Publishing states of gazebo models at [/ros2_grasp/model_states]
[gzserver-1] [INFO] [1726303444.628493688] [ros2_grasp.gazebo_ros_state]: Publishing states of gazebo links at [/ros2_grasp/link_states]
[spawn_entity.py-3] [INFO] [1726303446.888682752] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-3] [INFO] [1726303446.890085424] [spawn_entity]: Waiting for service /spawn_entity
[spawn_entity.py-3] [INFO] [1726303446.927743805] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-3] [INFO] [1726303447.310171903] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [ur5]
[INFO] [spawn_entity.py-3]: process has finished cleanly [pid 99774]
[INFO] [spawner-6]: process started with pid [99901]
[spawner-6] [INFO] [1726303450.434293065] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1726303452.461984292] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1726303454.482274185] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [INFO] [1726303456.510088404] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-6] [ERROR] [1726303458.526402037] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-6]: process has died [pid 99901, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
[INFO] [spawner-7]: process started with pid [100035]
[spawner-7] [INFO] [1726303461.163901169] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1726303463.183053866] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1726303465.198841988] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [INFO] [1726303467.219340783] [spawner_ur5_controller]: Waiting for '/controller_manager' node to exist
[spawner-7] [ERROR] [1726303469.243937676] [spawner_ur5_controller]: Controller manager not available
[ERROR] [spawner-7]: process has died [pid 100035, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner ur5_controller -c /controller_manager --ros-args'].
[INFO] [moveJ_action-8]: process started with pid [100142]
[INFO] [moveL_action-9]: process started with pid [100144]
[INFO] [moveR_action-10]: process started with pid [100146]
[INFO] [moveXYZ_action-11]: process started with pid [100148]
[INFO] [moveXYZW_action-12]: process started with pid [100150]
[INFO] [moveYPR_action-13]: process started with pid [100152]
[INFO] [moveROT_action-14]: process started with pid [100154]
[INFO] [moveRP_action-15]: process started with pid [100156]
[INFO] [attacher_action.py-16]: process started with pid [100158]
[moveXYZ_action-11] [INFO] [1726303472.906624511] [moveXYZ_action]: ROB_PARAM received -> ur5_arm
[moveXYZ_action-11] [WARN] [1726303472.933673977] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveL_action-9] [INFO] [1726303472.995665668] [moveL_action]: ROB_PARAM received -> ur5_arm
[moveL_action-9] [WARN] [1726303473.013623025] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveXYZW_action-12] [INFO] [1726303473.090451948] [moveXYZW_action]: ROB_PARAM received -> ur5_arm
[moveXYZW_action-12] [WARN] [1726303473.090720691] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveJ_action-8] [INFO] [1726303473.171994231] [moveJ_action]: ROB_PARAM received -> ur5_arm
[moveRP_action-15] [INFO] [1726303473.173551720] [moveRP_action]: ROB_PARAM received -> ur5_arm
[moveR_action-10] [INFO] [1726303473.178287896] [moveR_action]: ROB_PARAM received -> ur5_arm
[moveR_action-10] [WARN] [1726303473.182655460] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveJ_action-8] [WARN] [1726303473.182956334] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveRP_action-15] [WARN] [1726303473.209947077] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveXYZ_action-11] [INFO] [1726303473.214645929] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[moveXYZ_action-11] [INFO] [1726303473.214678235] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[moveXYZW_action-12] [INFO] [1726303473.319853681] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[moveXYZW_action-12] [INFO] [1726303473.319883919] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[moveL_action-9] [INFO] [1726303473.326215193] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[moveL_action-9] [INFO] [1726303473.326245504] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[moveYPR_action-13] [INFO] [1726303473.340157517] [moveYPR_action]: ROB_PARAM received -> ur5_arm
[moveROT_action-14] [INFO] [1726303473.350625203] [moveROT_action]: ROB_PARAM received -> ur5_arm
[moveROT_action-14] [WARN] [1726303473.350913268] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveYPR_action-13] [WARN] [1726303473.359058662] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[moveR_action-10] [INFO] [1726303473.445687238] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[moveR_action-10] [INFO] [1726303473.445719416] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[moveJ_action-8] [INFO] [1726303473.448066095] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[moveJ_action-8] [INFO] [1726303473.448090137] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[moveRP_action-15] [INFO] [1726303473.520539619] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[moveRP_action-15] [INFO] [1726303473.543602981] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[moveYPR_action-13] [INFO] [1726303473.714504548] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 26.057 seconds
[moveYPR_action-13] [INFO] [1726303473.714573254] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[moveROT_action-14] [INFO] [1726303473.811941567] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[moveROT_action-14] [INFO] [1726303473.811970719] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[INFO] [rviz2-17]: process started with pid [100342]
[INFO] [move_group-18]: process started with pid [100344]
[rviz2-17] qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
[move_group-18] [WARN] [1726303475.347453694] [move_group.move_group]: Falling back to using the the move_group node namespace (deprecated behavior).
[move_group-18] [INFO] [1726303475.358025720] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[move_group-18] [INFO] [1726303475.358064849] [moveit_robot_model.robot_model]: Loading robot model 'ur5'...
[move_group-18] [INFO] [1726303475.758855081] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-18] [INFO] [1726303475.760543026] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-18] [INFO] [1726303475.762698191] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-18] [INFO] [1726303475.763755013] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-18] [INFO] [1726303475.763769427] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-18] [INFO] [1726303475.764062812] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-18] [INFO] [1726303475.764074189] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-18] [INFO] [1726303475.764946873] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-18] [INFO] [1726303475.767909582] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-18] [WARN] [1726303475.772337502] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-18] [ERROR] [1726303475.772367070] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-18] [INFO] [1726303475.782398902] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'move_group'
[move_group-18] [INFO] [1726303475.841520764] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-18] [INFO] [1726303475.866395299] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.path_tolerance' was not set. Using default value: 0.100000
[move_group-18] [INFO] [1726303475.866462383] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.resample_dt' was not set. Using default value: 0.100000
[move_group-18] [INFO] [1726303475.866469223] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.min_angle_change' was not set. Using default value: 0.001000
[move_group-18] [INFO] [1726303475.866487977] [moveit_ros.fix_workspace_bounds]: Param 'move_group.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-18] [INFO] [1726303475.866502015] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_bounds_error' was set to 0.100000
[move_group-18] [INFO] [1726303475.866506603] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-18] [INFO] [1726303475.866518030] [moveit_ros.fix_start_state_collision]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-18] [INFO] [1726303475.866523031] [moveit_ros.fix_start_state_collision]: Param 'move_group.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-18] [INFO] [1726303475.866528039] [moveit_ros.fix_start_state_collision]: Param 'move_group.max_sampling_attempts' was not set. Using default value: 100
[move_group-18] [INFO] [1726303475.866537938] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-18] [INFO] [1726303475.866542936] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
[move_group-18] [INFO] [1726303475.866546464] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-18] [INFO] [1726303475.866549522] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-18] [INFO] [1726303475.866552271] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-18] [INFO] [1726303475.866586107] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-18] [INFO] [1726303476.000159040] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for ur5_controller
[move_group-18] [INFO] [1726303476.000291590] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-18] [INFO] [1726303476.000310622] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-18] [INFO] [1726303476.004251991] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-18] [INFO] [1726303476.004827021] [move_group.move_group]: MoveGroup debug mode is ON
[moveXYZ_action-11] [INFO] [1726303477.152765155] [move_group_interface]: Ready to take commands for planning group ur5_arm.
[moveL_action-9] [INFO] [1726303477.159081391] [move_group_interface]: Ready to take commands for planning group ur5_arm.
[move_group-18] [INFO] [1726303477.185427766] [move_group.move_group]: 
[move_group-18] 
[move_group-18] ********************************************************
[move_group-18] * MoveGroup using: 
[move_group-18] *     - ApplyPlanningSceneService
[move_group-18] *     - ClearOctomapService
[move_group-18] *     - CartesianPathService
[move_group-18] *     - ExecuteTrajectoryAction
[move_group-18] *     - GetPlanningSceneService
[move_group-18] *     - KinematicsService
[move_group-18] *     - MoveAction
[move_group-18] *     - MotionPlanService
[move_group-18] *     - QueryPlannersService
[move_group-18] *     - StateValidationService
[move_group-18] ********************************************************
[move_group-18] 
[move_group-18] [INFO] [1726303477.185474146] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
![image](https://github.com/user-attachments/assets/20df770f-f0c3-4cd3-9fa5-601f75424719)
However, in rviz, the display is normal but the plan is not moving
[move_group-18] [INFO] [1726303809.931904720] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[move_group-18] [INFO] [1726303809.932029022] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[rviz2-17] [INFO] [1726303809.938404200] [move_group_interface]: Plan and Execute request accepted
[move_group-18] [WARN] [1726303810.032223227] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock. Have been waiting for 0.000000s, timeout is 1.000000s
[move_group-18] [WARN] [1726303811.035972391] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock. Have been waiting for 0.956000s, timeout is 1.000000s
[move_group-18] [INFO] [1726303811.036003455] [moveit_ros.current_state_monitor]: Didn't receive robot state (joint angles) with recent timestamp within 1.000000 seconds. Requested time 335.138000, but latest received state has time 0.000000.
[move_group-18] Check clock synchronization if your are running ROS across multiple machines!
[move_group-18] [WARN] [1726303811.036013452] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Failed to fetch current robot state.
[move_group-18] [INFO] [1726303811.036043819] [moveit_move_group_default_capabilities.move_action_capability]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[move_group-18] [INFO] [1726303811.036069142] [moveit_ros.plan_execution]: Planning attempt 1 of at most 1
[move_group-18] [INFO] [1726303811.036075455] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'move_group'
[move_group-18] [INFO] [1726303811.036386491] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'ur5_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[move_group-18] [INFO] [1726303811.158244305] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-18] [INFO] [1726303811.158270300] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-18] [INFO] [1726303811.158290899] [moveit_ros.trajectory_execution_manager]: Validating trajectory with allowed_start_tolerance 0.01
[move_group-18] [WARN] [1726303812.061212924] [moveit_ros.current_state_monitor]: No state update received within 100ms of system clock. Have been waiting for 0.793000s, timeout is 1.000000s
[move_group-18] [INFO] [1726303812.161321210] [moveit_ros.current_state_monitor]: Didn't receive robot state (joint angles) with recent timestamp within 1.000000 seconds. Requested time 336.252000, but latest received state has time 0.000000.
[move_group-18] Check clock synchronization if your are running ROS across multiple machines!
[move_group-18] [WARN] [1726303812.161351499] [moveit_ros.trajectory_execution_manager]: Failed to validate trajectory: couldn't receive full current joint state within 1s
[move_group-18] [INFO] [1726303812.161411887] [moveit_move_group_default_capabilities.move_action_capability]: Solution found but controller failed during execution
[rviz2-17] [INFO] [1726303812.164181745] [move_group_interface]: Plan and Execute request aborted
[rviz2-17] [ERROR] [1726303812.165122840] [move_group_interface]: MoveGroupInterface::move() failed or timeout reached

**Comment by Swordsoulmeye** [comment]
please help me

**Comment by hrishikesh-st** [comment]
Hi @Swordsoulmeye I am facing the same issue. How did you resolve it?

**Comment by alicefasoli** [comment]
Hi, what's the solution to this problem? I have the same issue @Swordsoulmeye  @hrishikesh-st

**Comment by Swordsoulmeye** [comment]
IFRA-Cranfield/ros2_RobotSimulation#26 （评论）see this@alicefasoli

**Comment by Swordsoulmeye** [comment]
https://github.com/IFRA-Cranfield/ros2_RobotSimulation/issues/26 （评论）@hrishikesh-st，see this， may help

**Comment by Swordsoulmeye** [comment]
> Hi, what's the solution to this problem? I have the same issue @Swordsoulmeye @hrishikesh-st

https://github.com/IFRA-Cranfield/ros2_RobotSimulation/issues/26 （评论），see this， may help
