### ISSUE TITLE
All launchs with triggers/action fails ( humble )

### ISSUE THREAD

**Issue by FrGe2016** [IFRA-Cranfield/ros2_RobotSimulation#6]
Here are the error messages for ros2 launch ur10_ros2_moveit2 ur10_interface.launch.py ( typical of all robots tried)

[Testing log trigers actions.txt](https://github.com/IFRA-Cranfield/ros2_RobotSimulation/files/10893636/Testing.log.trigers.actions.txt)

**Comment by FrGe2016** [comment]
I have done may test related to the ros2_action and and ros2_executions

Here are a few comments :
One build error for ros2_execution "abb-robot_msgs was missing in 
 Import SERVICES:
from abb_robot_msgs.srv import SetIOSignal

I added  a  .srv directory to ros2_data, 
            copied the SetIOSignal.srv file from the abb_robot_driver_interfaces
            Added    "srv/SetIOSignal.srv" in the CMakeLists.txt in the # ADD ROS2.0 .msg, .srv and .action files: section
            
            modified line 57 of execuion.py
            #from abb_robot_msgs.srv import SetIOSignal
             from ros2_data.srv import SetIOSignal

I had two problems with irb120_interface.launch.py
       egp64_RightFinger.dae was missing I reanmed the "Schunk Gripper - RIGHT FINGER.dae"
       Had to comment Attacher ( it had a file not found message, but it is in the specified directory ???)
            [ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'attacher_action.py' 
            not found on the libexec directory '/home/francois/dev_ws/install/ros2_grasping/lib/ros2_grasping' 
 
Since attacher is not started scripts involving grasping are not working

**Comment by MikelBueno** [comment]
Hi @FrGe2016,

Thank you very much for your feedback.

With regard to your last message:
* The abb_robot_msgs service is not needed for these simulations (I have removed it in the latest commit).
* "egp64_RightFinger.dae" is how I have named the file in ROS2 Humble and "Schunk Gripper - RIGHT FINGER.dae" is how it is called in the ROS2 Foxy branch. Could you please check that you've imported the correct branch for your ROS2 version?
* attacher_action.py is under ros2_grasping/scripts, and it is installed through the package's CMakeLists.txt file (check the last lines). It should be working...

As I've mentioned, please check that you've installed the correct branch, and do let me know if you have any problems.

Best regards,
Mikel

**Comment by FrGe2016** [comment]
Hi

In humble "egp64_RightFinger.dae" is required in the URDF but the file is not renamed in /irb120_ros2_gazebo/meshes)/egp64/ 
i have fixed it machine but the package could be modified to avoid this manual fix.

About attacher_action.py
        It is effectively under ros2_grasping/scripts, and it is installed through the package's CMakeLists.txt file
        it is also at the right place after build /home/francois/dev_ws/install/ros2_grasping/lib/ros2_grasping
        but for some unknown reason it is not found when i launch the package ??
ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'attacher_action.py'
not found on the libexec directory '/home/francois/dev_ws/install/ros2_grasping/lib/ros2_grasping'

Finally solved

Was compile with colcon build --symlink-install the the symlink was not executable
Solution 1 : build without --syslink-install
Solution 2 : have the 2 python files executable in the source directory with chmod ( my prefered solution )

**Comment by FrGe2016** [comment]
Very interesting package

Here are a few improvement proposals : 
      - in the launch file date entry prompt remove the N before the number of the option since only the number must be typed
      - for the read me of ros2 execution have a full exemple of the steps required for the sequences involving pick and pace (ex: cubePP.txt) 

ros2 launch irb120_ros2_moveit2 irb120_interface.launch.py
	Option 3: ABB IRB-120 Pick&Place Use-Case
	Option 3: Schunk EGP-64 parallel gripper
ros2 run ros2_grasping spawn_object.py --package "ros2_grasping" --urdf "box.urdf" --name "box" --x 0.5 --y -0.3 --z 0.75
ros2 run ros2_execution ros2_execution.py --ros-args -p PROGRAM_FILENAME:="cubePP" -p ROBOT_MODEL:="irb120" -p EE_MODEL:="schunk"

Regards Francois
