### ISSUE TITLE
README mistake in humble branch

### ISSUE THREAD

**Issue by Zyonia** [IFRA-Cranfield/ros2_RobotSimulation#9]
> Fix cycle time issues in humble-moveit (temporary fix):
```
sudo apt install ros-rolling-rmw-cyclonedds-cpp
Add into .bashrc file -> export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
```
I wonder is that should be :
```
sudo apt install ros-humble-rmw-cyclonedds-cpp
```
If i am wrong, please ignore me.  :-p

**Comment by MikelBueno** [comment]
Hi Zyonia,

Yes, you are correct, thank you very much!
I will update it right now.

Regards,
Mikel
